[tox]
requires =
    tox>=4.32
env_list = py3{12-15}-sphinx{8,9}, coverage

[testenv]
extras =
    dev
pass_env =
    FORCE_COLOR
deps =
    sphinx8: sphinx>8,<9
    sphinx9: sphinx>9,<10
commands =
    coverage run -m pytest {posargs}

[testenv:coverage]
depends = py3*
commands =
    coverage combine -q
    coverage report -m
    coverage html
